### ISSUE TITLE
configure deployment with rultor

### ISSUE THREAD

**Issue by ammaratef45** [ammaratef45/Attendance#1]
use rultor and Fastlane for CI/CD

**Comment by 0pdd** [comment]
@ammaratef45 the puzzle [#13](https://github.com/ammaratef45/Attendance/issues/13) is still not solved.

**Comment by 0pdd** [comment]
@ammaratef45 the only puzzle [#13](https://github.com/ammaratef45/Attendance/issues/13) is solved here.
