### ISSUE TITLE
App fails to login for no clear reason

### ISSUE THREAD

**Issue by Bahaaib** [ammaratef45/Attendance#10]
**Summary:** 
Once the App finally is installed and loaded successfully on device. I try to sign in using "Sign in" Green Button. My Google accounts dialoge pops up to me to select an account. I did select all possible accounts in several different trials to log in be it all ended up to NO RESPOND. Neither FAILED nor home activity appeared. I tried to debug the source code to to figure out if it was TIMEOUT network from my side and it is NOT.

**Steps to reproduce:**
1- Install the App normally and open it
2- Try to Sign in using your Google account

**System logs:**
No crucial logs might help in my case but interestingly i detected Authentication libraries deprecation. Actually All the used Firebase libraries threw the same warning..

`..../FirebaseAuthPlugin.java uses or overrides a deprecated API.
`   
**Device and Android version:** 
Device: Infinix HOT 5
Android version: Android 7.0

**Comment by ammaratef45** [comment]
@Bahaaib sorry, I didn't mention that in the README file, you have to provide me with the development fingerprint sha-1 and I will allow you to build 👍

**Comment by ammaratef45** [comment]
@Bahaaib I've added [this section](https://github.com/ammaratef45/Attendance/blob/master/README.md#ho-to-contribute) to the README, check it out.

**Comment by Bahaaib** [comment]
neat !
