### ISSUE TITLE
add save to attendance model

### ISSUE THREAD

**Issue by 0pdd** [ammaratef45/Attendance#100]
The puzzle `50-d7dab752` from #50 has to be resolved: 

https://github.com/ammaratef45/Attendance/blob/76cc877614a5299c42cbdc65568e70ef27dd3caa/attendance/lib/backend/user.dart#L138-L138

The puzzle was created by Ammar Atef on 08-May-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
The puzzle `50-d7dab752` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:ammaratef45/attendance#100` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
