### ISSUE TITLE
Ambiguous Error message on scanning random barcodes 

### ISSUE THREAD

**Issue by Bahaaib** [ammaratef45/Attendance#11]
**Summary:** 
When i log in to my home activity and launch my camera to scan a random barcode. The resultant message depends on different cases. All the barcodes are wrong but the response is not the same. Below i mentioned 2 remarkable cases. Otherwise, The camera was trying to scan forever without any time barriers.

**Steps to reproduce:**
1- Install the App and open it normally
2- Log in via "Offline mode" 
3- Press the bottom-right floating button to launch the camera
4- try to scan the attached barcodes below 
  **Case 1:**
<a href="https://imgur.com/ax9yQdy"><img src="https://i.imgur.com/ax9yQdy.png" title="source: imgur.com" /></a>

**Case 2:**

<a href="https://imgur.com/1gVWajA.png"><img src="https://i.imgur.com/1gVWajA.png" title="source: imgur.com" /></a>

**Screenshots:**

**Case 1:**

<a href="https://imgur.com/jkYRfOP.png"><img src="https://i.imgur.com/jkYRfOP.png" title="source: imgur.com" /></a>

**Case2:**

<a href="https://imgur.com/HBbBBgW.png"><img src="https://i.imgur.com/HBbBBgW.png" title="source: imgur.com" /></a>

**Device and Android version:**
Device: Infinix HOT 5
Android version: Android 7.0

**Comment by ammaratef45** [comment]
@Bahaaib This isn't a bug, those codes aren't generated by our [Admin](https://github.com/ammaratef45/Attendance-Admin) App, maybe the error code isn't clear enough.
We should show the user the format of the scanned code and what format we are expecting.
Thanks for reporting this, want to work on it? I can assign it to you

**Comment by Bahaaib** [comment]
Oh. That's my mistake to give it that title. It's not a bug for sure but the content has no use at all. I'll happily take it

**Comment by ammaratef45** [comment]
@Bahaaib Okay
I've added your sha-1 so that you can log in.
I suggest you add a module like [that](https://github.com/ammaratef45/zold-flutter-client/blob/master/zold_wallet/lib/dialogs.dart), if you intend to leave any work incomplete (I suggest you to do that if the PR is going large) just add a puzzle like this
```
// @todo #11 complete this by adding bla bla and so on
```
Thanks for the contribution :+1:

**Comment by ammaratef45** [comment]
@Bahaaib Now you can close the issue (I guess)

**Comment by 0crat** [comment]
Job `gh:ammaratef45/attendance#11` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
