### ISSUE TITLE
learn how to use test and write unit tests

### ISSUE THREAD

**Issue by 0pdd** [ammaratef45/Attendance#13]
The puzzle `1-32499cde` from #1 has to be resolved: 

https://github.com/ammaratef45/Attendance/blob/f32c2774879475c374b58a7557860f567af12048/attendance/test/widget_test.dart#L15-L15

The puzzle was created by @ammaratef45 on 25-Mar-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#13](https://github.com/ammaratef45/attendance/issues/13) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#13](https://github.com/ammaratef45/attendance/issues/13) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CH951175M/20e6b276-62f7-4f7c-8bbe-ea500748d93b); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `1-32499cde` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#13](https://github.com/ammaratef45/attendance/issues/13) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)
