### ISSUE TITLE
Login page doesn't follow Google material design Guidelines

### ISSUE THREAD

**Issue by Bahaaib** [ammaratef45/Attendance#18]
**Summary:**
Login page looks too simple than it should be as a potential grown App. The page doesn't follow any UI/UX roles. It's just hit and run. So i tried to add some sort of life to it.

**Screenshots:*
To be added..

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please, pay attention to this issue

**Comment by 0crat** [comment]
@bahaaib[/z](https://www.0crat.com/u/bahaaib) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CH951175M) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Thanks for your contribution, @bahaaib[/z](https://www.0crat.com/u/bahaaib)! If you would be a member of [the project](https://www.0crat.com/p/CH951175M), you would now earn +15 reputation points, as explained in [§29](http://www.zerocracy.com/policy.html#29). You can join and apply to it, see [§2](http://www.zerocracy.com/policy.html#2).

**Comment by 0crat** [comment]
The job [#18](https://github.com/ammaratef45/attendance/issues/18) assigned to @bahaaib[/z](https://www.0crat.com/u/bahaaib), here is [why](https://www.0crat.com/footprint/CH951175M/2a5ab23b-3b7f-473a-93ac-089d91196b6b); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @bahaaib[/z](https://www.0crat.com/u/bahaaib) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by ammaratef45** [comment]
@Bahaaib Thaks :+1:

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#18](https://github.com/ammaratef45/attendance/issues/18) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @bahaaib[/z](https://www.0crat.com/u/bahaaib)
