### ISSUE TITLE
Use performance tools

### ISSUE THREAD

**Issue by ammaratef45** [ammaratef45/Attendance#22]
Flutter have some tools to ensure performance like in [this](https://github.com/flutter/devtools) repo

We should integrate some of them to have a suitable track of performance

Then document this in the how to contribute section, encourage contributors to care about this too

**Comment by 0crat** [comment]
Job [#22](https://github.com/ammaratef45/attendance/issues/22) is now in scope, role is `DEV`

**Comment by ammaratef45** [comment]
@Bahaaib you may want to have a look on this, these tools are late already :laughing:

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) everybody who has role `DEV` is banned at [#22](https://github.com/ammaratef45/attendance/issues/22); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) everybody who has role `DEV` is banned at [#22](https://github.com/ammaratef45/attendance/issues/22); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) everybody who has role `DEV` is banned at [#22](https://github.com/ammaratef45/attendance/issues/22); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
You @bahaaib[/z](https://www.0crat.com/u/bahaaib) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by ammaratef45** [comment]
@0crat assign @Bahaaib

**Comment by 0crat** [comment]
> @0crat assign @Bahaaib ([here](https://github.com/ammaratef45/Attendance/issues/22#issuecomment-482119820))

@ammaratef45 The job [#22](https://github.com/ammaratef45/attendance/issues/22) assigned to @bahaaib[/z](https://www.0crat.com/u/bahaaib), here is [why](https://www.0crat.com/footprint/CH951175M/9f55562c-e0df-4314-b279-01c7ece20462); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @bahaaib[/z](https://www.0crat.com/u/bahaaib) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by ammaratef45** [comment]
@Bahhaib thanks

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#22](https://github.com/ammaratef45/attendance/issues/22) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @bahaaib[/z](https://www.0crat.com/u/bahaaib)
