### ISSUE TITLE
Update..

### ISSUE THREAD

**Issue by 0pdd** [ammaratef45/Attendance#24]
The puzzle `21-20ae1e1a` from #21 has to be resolved: 

https://github.com/ammaratef45/Attendance/blob/9f6a8fd62dbe74ab63635d65df334098944ad00c/attendance/lib/ProfilePage/profile_page_view.dart#L167-L167

The puzzle was created by @ammaratef45 on 06-Apr-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#24](https://github.com/ammaratef45/attendance/issues/24) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#24](https://github.com/ammaratef45/attendance/issues/24) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CH951175M/dbe5f5d1-a51f-4a9c-9fea-4b30fca37ab9); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `21-20ae1e1a` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job was finished in 35 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#24](https://github.com/ammaratef45/attendance/issues/24) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)
