### ISSUE TITLE
save the model to the API and save locally if failed to connect to the API

### ISSUE THREAD

**Issue by 0pdd** [ammaratef45/Attendance#26]
The puzzle `25-e6ecf1e1` from #25 has to be resolved: 

https://github.com/ammaratef45/Attendance/blob/b811652615720f37c8e4c9bc53a4e05a540580a2/attendance/lib/BackEnd/user.dart#L32-L32

The puzzle was created by Ammar Atef on 08-Apr-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#26](https://github.com/ammaratef45/attendance/issues/26) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#26](https://github.com/ammaratef45/attendance/issues/26) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CH951175M/b80cb003-fb84-457a-8f6b-eb393892d32f); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `25-e6ecf1e1` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 5 puzzles [#37](https://github.com/ammaratef45/Attendance/issues/37), [#38](https://github.com/ammaratef45/Attendance/issues/38), [#39](https://github.com/ammaratef45/Attendance/issues/39), [#40](https://github.com/ammaratef45/Attendance/issues/40), [#41](https://github.com/ammaratef45/Attendance/issues/41) are still not solved.

**Comment by 0crat** [comment]
The job [#26](https://github.com/ammaratef45/attendance/issues/26) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0pdd** [comment]
@0pdd 4 puzzles [#38](https://github.com/ammaratef45/Attendance/issues/38), [#39](https://github.com/ammaratef45/Attendance/issues/39), [#40](https://github.com/ammaratef45/Attendance/issues/40), [#41](https://github.com/ammaratef45/Attendance/issues/41) are still not solved; solved: [#37](https://github.com/ammaratef45/Attendance/issues/37).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#40](https://github.com/ammaratef45/Attendance/issues/40), [#41](https://github.com/ammaratef45/Attendance/issues/41) are still not solved; solved: [#37](https://github.com/ammaratef45/Attendance/issues/37), [#38](https://github.com/ammaratef45/Attendance/issues/38), [#39](https://github.com/ammaratef45/Attendance/issues/39).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#40](https://github.com/ammaratef45/Attendance/issues/40), [#54](https://github.com/ammaratef45/Attendance/issues/54) are still not solved; solved: [#37](https://github.com/ammaratef45/Attendance/issues/37), [#38](https://github.com/ammaratef45/Attendance/issues/38), [#39](https://github.com/ammaratef45/Attendance/issues/39), [#41](https://github.com/ammaratef45/Attendance/issues/41).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#40](https://github.com/ammaratef45/Attendance/issues/40) is still not solved; solved: [#37](https://github.com/ammaratef45/Attendance/issues/37), [#38](https://github.com/ammaratef45/Attendance/issues/38), [#39](https://github.com/ammaratef45/Attendance/issues/39), [#41](https://github.com/ammaratef45/Attendance/issues/41), [#54](https://github.com/ammaratef45/Attendance/issues/54).
