### ISSUE TITLE
Add lint checker

### ISSUE THREAD

**Issue by ammaratef45** [ammaratef45/Attendance#28]
[see this](https://medium.com/flutter-community/watch-your-code-dart-flutter-lint-55a697d01c8d) and add lint checking to the repository.

**Comment by 0crat** [comment]
Job `gh:ammaratef45/attendance#28` already assigned to @ammaratef45, can't assign to @ammaratef45

**Comment by 0crat** [comment]
The job [#28](https://github.com/ammaratef45/attendance/issues/28) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CH951175M/3bf0d388-13ac-4621-8c7c-be71d2369420); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0pdd** [comment]
@ammaratef45 the puzzle [#36](https://github.com/ammaratef45/Attendance/issues/36) is still not solved.

**Comment by 0crat** [comment]
The job [#28](https://github.com/ammaratef45/attendance/issues/28) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0pdd** [comment]
@ammaratef45 the puzzle [#44](https://github.com/ammaratef45/Attendance/issues/44) is still not solved; solved: [#36](https://github.com/ammaratef45/Attendance/issues/36).

**Comment by 0pdd** [comment]
@ammaratef45 all 2 puzzles are solved here: [#36](https://github.com/ammaratef45/Attendance/issues/36), [#44](https://github.com/ammaratef45/Attendance/issues/44).
