### ISSUE TITLE
activate commented tests after implementing validation methods

### ISSUE THREAD

**Issue by 0pdd** [ammaratef45/Attendance#30]
The puzzle `31-1d05e01b` from #31 has to be resolved: 

https://github.com/ammaratef45/Attendance/blob/a2a27b7296839ea0c67d070aadb37ab7c611f300/attendance/test/userdata_test.dart#L12-L12

The puzzle was created by @Bahaaib on 10-Apr-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#32](https://github.com/ammaratef45/Attendance/issues/32) is still not solved.

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#30](https://github.com/ammaratef45/attendance/issues/30) is now in scope, role is `DEV`

**Comment by 0pdd** [comment]
The puzzle `31-1d05e01b` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#32](https://github.com/ammaratef45/Attendance/issues/32) is solved here.

**Comment by 0crat** [comment]
Job `gh:ammaratef45/attendance#30` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#30](https://github.com/ammaratef45/attendance/issues/30) is now out of scope
