### ISSUE TITLE
validate native name and phone number format

### ISSUE THREAD

**Issue by 0pdd** [ammaratef45/Attendance#31]
The puzzle `29-6a4b732b` from #29 has to be resolved: 

https://github.com/ammaratef45/Attendance/blob/a2a27b7296839ea0c67d070aadb37ab7c611f300/attendance/lib/BackEnd/user.dart#L35-L35

The puzzle was created by @Bahaaib on 10-Apr-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#30](https://github.com/ammaratef45/Attendance/issues/30) is still not solved.

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#31](https://github.com/ammaratef45/attendance/issues/31) is now in scope, role is `DEV`

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#30](https://github.com/ammaratef45/Attendance/issues/30), [#32](https://github.com/ammaratef45/Attendance/issues/32) are still not solved.

**Comment by 0crat** [comment]
You @bahaaib[/z](https://www.0crat.com/u/bahaaib) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0pdd** [comment]
The puzzle `29-6a4b732b` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:ammaratef45/attendance#31` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#31](https://github.com/ammaratef45/attendance/issues/31) is now out of scope

**Comment by 0pdd** [comment]
@0pdd all 2 puzzles are solved here: [#30](https://github.com/ammaratef45/Attendance/issues/30), [#32](https://github.com/ammaratef45/Attendance/issues/32).
