### ISSUE TITLE
check Singleton potential leak

### ISSUE THREAD

**Issue by 0pdd** [ammaratef45/Attendance#32]
The puzzle `30-102e74fa` from #30 has to be resolved: 

https://github.com/ammaratef45/Attendance/blob/a2a27b7296839ea0c67d070aadb37ab7c611f300/attendance/lib/BackEnd/user.dart#L36-L36

The puzzle was created by @Bahaaib on 10-Apr-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#32](https://github.com/ammaratef45/attendance/issues/32) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#32](https://github.com/ammaratef45/attendance/issues/32) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CH951175M/780a318f-9a64-4e44-9085-60b31f8cb7a1); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by ammaratef45** [comment]
@Bahaaib what is meant by the leak? It's meant to keep its value all the time it is in memory, right?

**Comment by Bahaaib** [comment]
Singleton leakage is the capability of allocating multiple instances of it.

**Comment by Bahaaib** [comment]
Sorry! I've just noticed you've been assigned to the issue. Should that be a problem?

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) I see that you unassigned this issue; the order is still assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45) though; to cancel the order use `refuse`, as in [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
The job [#32](https://github.com/ammaratef45/attendance/issues/32) assigned to @bahaaib[/z](https://www.0crat.com/u/bahaaib), here is [why](https://www.0crat.com/footprint/CH951175M/0d86c38f-2ac4-48b7-ba72-ea170c7325da); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @bahaaib[/z](https://www.0crat.com/u/bahaaib) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by ammaratef45** [comment]
@Bahaaib It's okay, generally wait for being assigned then work on the issue (to avoid wasting time on the same issue)

**Comment by 0pdd** [comment]
The puzzle `30-102e74fa` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#32](https://github.com/ammaratef45/attendance/issues/32) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @bahaaib[/z](https://www.0crat.com/u/bahaaib)
