### ISSUE TITLE
uncomment rules and fix related problems

### ISSUE THREAD

**Issue by 0pdd** [ammaratef45/Attendance#36]
The puzzle `28-7c1deb1b` from #28 has to be resolved: 

https://github.com/ammaratef45/Attendance/blob/e3f25225ec5f9253f369cd4c9231caa61da43663/attendance/analysis_options.yaml#L36-L36

The puzzle was created by Ammar Atef on 12-Apr-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#36](https://github.com/ammaratef45/attendance/issues/36) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#36](https://github.com/ammaratef45/attendance/issues/36) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CH951175M/884458bd-7cbb-48b8-93b6-668b60688ba4); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0pdd** [comment]
The puzzle `28-7c1deb1b` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#44](https://github.com/ammaratef45/Attendance/issues/44) is still not solved.

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#36](https://github.com/ammaratef45/attendance/issues/36) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#44](https://github.com/ammaratef45/Attendance/issues/44) is solved here.
