### ISSUE TITLE
trim the inputs before validation for rename and changePhone

### ISSUE THREAD

**Issue by 0pdd** [ammaratef45/Attendance#37]
The puzzle `26-5befb100` from #26 has to be resolved: 

https://github.com/ammaratef45/Attendance/blob/eca2402ae6ed995f3e2a51ecbbc94e2b448d44e6/attendance/lib/BackEnd/user.dart#L23-L23

The puzzle was created by Ammar Atef on 13-Apr-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#37](https://github.com/ammaratef45/attendance/issues/37) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#37](https://github.com/ammaratef45/attendance/issues/37) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CH951175M/d01486cf-d5ac-4993-9a1e-9df90ab02af3); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `26-5befb100` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#37](https://github.com/ammaratef45/attendance/issues/37) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)
