### ISSUE TITLE
Implement markSaved so that it changes the falg saved to true.

### ISSUE THREAD

**Issue by 0pdd** [ammaratef45/Attendance#39]
The puzzle `26-1a7fd9bd` from #26 has to be resolved: 

https://github.com/ammaratef45/Attendance/blob/eca2402ae6ed995f3e2a51ecbbc94e2b448d44e6/attendance/lib/BackEnd/user.dart#L81-L81

The puzzle was created by Ammar Atef on 13-Apr-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#39](https://github.com/ammaratef45/attendance/issues/39) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0pdd** [comment]
The puzzle `26-1a7fd9bd` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
I'm not managing `ammaratef45/attendance` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by ammaratef45** [comment]
@0crat status

**Comment by 0crat** [comment]
I'm not managing `ammaratef45/attendance` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by ammaratef45** [comment]
@0crat status

**Comment by 0crat** [comment]
I'm not managing `ammaratef45/attendance` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by ammaratef45** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/ammaratef45/Attendance/issues/39#issuecomment-483636895))

@ammaratef45 This is what I know about this job in [CH951175M](https://www.0crat.com/p/CH951175M), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#39](https://github.com/ammaratef45/attendance/issues/39) is [in scope](http://www.zerocracy.com/policy.html#14) for 3days
  * The role is `DEV`
  * The job is assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45) for [2days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @0pdd[/z](https://www.0crat.com/u/0pdd): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/CH951175M?q=%7Bjob%3A%27gh%3Aammaratef45%2Fattendance%2339%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please, pay attention to this issue

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
The job [#39](https://github.com/ammaratef45/attendance/issues/39) is now out of scope
