### ISSUE TITLE
show error below the entry field if failed to set the value to the user object.

### ISSUE THREAD

**Issue by 0pdd** [ammaratef45/Attendance#41]
The puzzle `26-eb936c7c` from #26 has to be resolved: 

https://github.com/ammaratef45/Attendance/blob/eca2402ae6ed995f3e2a51ecbbc94e2b448d44e6/attendance/lib/ProfilePage/profile_page_viewmodel.dart#L7-L8

The puzzle was created by Ammar Atef on 13-Apr-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please, pay attention to this issue

**Comment by ammaratef45** [comment]
@Bahaaib want to take this?

**Comment by 0crat** [comment]
The job [#41](https://github.com/ammaratef45/attendance/issues/41) assigned to @bahaaib[/z](https://www.0crat.com/u/bahaaib), here is [why](https://www.0crat.com/footprint/CH951175M/b6d1ba80-e8e9-4c15-a82b-3afc5d0d1759); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @bahaaib[/z](https://www.0crat.com/u/bahaaib) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by Bahaaib** [comment]
@ammaratef45 Okay

**Comment by 0crat** [comment]
@bahaaib[/z](https://www.0crat.com/u/bahaaib) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0pdd** [comment]
The puzzle `26-eb936c7c` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job [#41](https://github.com/ammaratef45/attendance/issues/41) is not in the agenda of @bahaaib[/z](https://www.0crat.com/u/bahaaib), can't retrieve data and time of add

**Comment by 0crat** [comment]
The job [#41](https://github.com/ammaratef45/attendance/issues/41) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @bahaaib[/z](https://www.0crat.com/u/bahaaib)
