### ISSUE TITLE
Use Map object to create a testing json body

### ISSUE THREAD

**Issue by 0pdd** [ammaratef45/Attendance#43]
The puzzle `42-871903c1` from #42 has to be resolved: 

https://github.com/ammaratef45/Attendance/blob/b6a094b60e9a355a469d4cb1430b538049f0288b/attendance/test/userdata_test.dart#L9-L9

The puzzle was created by @Bahaaib on 13-Apr-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `42-871903c1` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
The job [#43](https://github.com/ammaratef45/attendance/issues/43) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CH951175M/a22a9b4d-1404-4070-97ae-5715570d8f48); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#43](https://github.com/ammaratef45/attendance/issues/43) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)
