### ISSUE TITLE
use /newsession instead of database as in online

### ISSUE THREAD

**Issue by 0pdd** [ammaratef45/Attendance#45]
The puzzle `9-721f19e1` from #9 has to be resolved: 

https://github.com/ammaratef45/Attendance/blob/6458784661c60ff240bc92347d7306a070af4ac8/attendance/lib/offline_page/offline_page_viewmodel.dart#L118-L118

The puzzle was created by Ammar Atef on 16-Apr-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:ammaratef45/attendance#45` already assigned to @ammaratef45, can't assign to @ammaratef45

**Comment by 0crat** [comment]
The job [#45](https://github.com/ammaratef45/attendance/issues/45) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CH951175M/609f0cd6-908b-442a-ad99-1d9fa9082e42); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0pdd** [comment]
The puzzle `9-721f19e1` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#94](https://github.com/ammaratef45/Attendance/issues/94), [#95](https://github.com/ammaratef45/Attendance/issues/95) are still not solved.

**Comment by 0crat** [comment]
Job was finished in 7 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#45](https://github.com/ammaratef45/attendance/issues/45) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)
