### ISSUE TITLE
just update the user class and call save

### ISSUE THREAD

**Issue by 0pdd** [ammaratef45/Attendance#47]
The puzzle `9-5930cbef` from #9 has to be resolved: 

https://github.com/ammaratef45/Attendance/blob/6458784661c60ff240bc92347d7306a070af4ac8/attendance/lib/loginPage/login_page_viewmodel.dart#L39-L39

The puzzle was created by Ammar Atef on 16-Apr-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `9-5930cbef` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:ammaratef45/attendance#47` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
