### ISSUE TITLE
save locally and call api /newsession instead of using firebase database

### ISSUE THREAD

**Issue by 0pdd** [ammaratef45/Attendance#48]
The puzzle `9-714752f5` from #9 has to be resolved: 

https://github.com/ammaratef45/Attendance/blob/6458784661c60ff240bc92347d7306a070af4ac8/attendance/lib/homePage/home_page_viewmodel.dart#L56-L56

The puzzle was created by Ammar Atef on 16-Apr-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#48](https://github.com/ammaratef45/attendance/issues/48) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CH951175M/1a70cf73-b28a-4382-be30-3f2c0275aec2); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0pdd** [comment]
The puzzle `9-714752f5` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#69](https://github.com/ammaratef45/Attendance/issues/69), [#70](https://github.com/ammaratef45/Attendance/issues/70), [#71](https://github.com/ammaratef45/Attendance/issues/71) are still not solved.

**Comment by 0crat** [comment]
Job was finished in 21 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#48](https://github.com/ammaratef45/attendance/issues/48) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#104](https://github.com/ammaratef45/Attendance/issues/104), [#70](https://github.com/ammaratef45/Attendance/issues/70) are still not solved; solved: [#69](https://github.com/ammaratef45/Attendance/issues/69), [#71](https://github.com/ammaratef45/Attendance/issues/71).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#104](https://github.com/ammaratef45/Attendance/issues/104) is still not solved; solved: [#69](https://github.com/ammaratef45/Attendance/issues/69), [#70](https://github.com/ammaratef45/Attendance/issues/70), [#71](https://github.com/ammaratef45/Attendance/issues/71).
