### ISSUE TITLE
save locally and call api /sessionleave instead of using firebase database

### ISSUE THREAD

**Issue by 0pdd** [ammaratef45/Attendance#51]
The puzzle `9-e42e0be6` from #9 has to be resolved: 

https://github.com/ammaratef45/Attendance/blob/6458784661c60ff240bc92347d7306a070af4ac8/attendance/lib/AttendanceDatailsPage/attendance_details_page_viewmodel.dart#L61-L61

The puzzle was created by Ammar Atef on 16-Apr-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#51](https://github.com/ammaratef45/attendance/issues/51) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CH951175M/5a2cae06-4ad3-48fb-a29b-5b3fabe78bf0); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please, pay attention to this issue

**Comment by 0crat** [comment]
GitHub issue is still open, won't close

**Comment by ammaratef45** [comment]
@0crat wait

**Comment by 0crat** [comment]
> @0crat wait ([here](https://github.com/ammaratef45/Attendance/issues/51#issuecomment-487069937))

@ammaratef45 The impediment for [#51](https://github.com/ammaratef45/attendance/issues/51) was registered successfully by @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0pdd** [comment]
The puzzle `9-e42e0be6` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#59](https://github.com/ammaratef45/Attendance/issues/59), [#60](https://github.com/ammaratef45/Attendance/issues/60), [#61](https://github.com/ammaratef45/Attendance/issues/61) are still not solved.

**Comment by 0crat** [comment]
The job [#51](https://github.com/ammaratef45/attendance/issues/51) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#105](https://github.com/ammaratef45/Attendance/issues/105), [#98](https://github.com/ammaratef45/Attendance/issues/98) are still not solved; solved: [#59](https://github.com/ammaratef45/Attendance/issues/59), [#60](https://github.com/ammaratef45/Attendance/issues/60), [#61](https://github.com/ammaratef45/Attendance/issues/61).
