### ISSUE TITLE
Clean Profile module from Dart Warnings

### ISSUE THREAD

**Issue by Bahaaib** [ammaratef45/Attendance#52]
Profile Module needs to follow Effective Dart Guideline Documentation here:
https://www.dartlang.org/guides/language/effective-dart/usage

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please, pay attention to this issue

**Comment by 0crat** [comment]
@bahaaib[/z](https://www.0crat.com/u/bahaaib) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CH951175M) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job `gh:ammaratef45/attendance#52` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
