### ISSUE TITLE
show error below the entry field if failed to

### ISSUE THREAD

**Issue by 0pdd** [ammaratef45/Attendance#54]
The puzzle `26-9d0688a2` from #26 has to be resolved: 

https://github.com/ammaratef45/Attendance/blob/4215e74989f15d4bb9fad93d950309d6d7d7cf35/attendance/lib/ProfilePage/profile_page_viewmodel.dart#L7-L7

The puzzle was created by @ammaratef45 on 24-Apr-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#54](https://github.com/ammaratef45/attendance/issues/54) assigned to @bahaaib[/z](https://www.0crat.com/u/bahaaib), here is [why](https://www.0crat.com/footprint/CH951175M/fb76e36e-bf9b-400e-b541-f62bdf36448c); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @bahaaib[/z](https://www.0crat.com/u/bahaaib) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0pdd** [comment]
The puzzle `26-9d0688a2` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job was finished in 45 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#54](https://github.com/ammaratef45/attendance/issues/54) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @bahaaib[/z](https://www.0crat.com/u/bahaaib)
