### ISSUE TITLE
Update docker file

### ISSUE THREAD

**Issue by ammaratef45** [ammaratef45/Attendance#57]
The docker image should be extended to have pdd installed to make rultor faster

**Comment by 0crat** [comment]
The job [#57](https://github.com/ammaratef45/attendance/issues/57) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CH951175M/cc5badc5-858b-43fd-9d8f-5935be839c89); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
The job [#57](https://github.com/ammaratef45/attendance/issues/57) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)
