### ISSUE TITLE
mock a session for this test and make it work.

### ISSUE THREAD

**Issue by 0pdd** [ammaratef45/Attendance#61]
The puzzle `51-f4bdd362` from #51 has to be resolved: 

https://github.com/ammaratef45/Attendance/blob/8e65cc4c6bf19ce33986a9cdaac3e67901e53542/attendance/test/api_test.dart#L40-L40

The puzzle was created by Ammar Atef on 26-Apr-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `51-f4bdd362` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:ammaratef45/attendance#61` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
