### ISSUE TITLE
Replace the scan Tab with FAB in Homepage

### ISSUE THREAD

**Issue by Bahaaib** [ammaratef45/Attendance#62]
**Summary**
The Scan Tab seems violating the material design guidelines as its behavior is not compatible with the other tabs. (2 Tabs display data and 1 taking actions). 
The tab corresponding actions would be took over by a FAB which is the most convenient candidate to the job

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please, pay attention to this issue

**Comment by 0crat** [comment]
@bahaaib[/z](https://www.0crat.com/u/bahaaib) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CH951175M) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0pdd** [comment]
@Bahaaib the puzzle [#64](https://github.com/ammaratef45/Attendance/issues/64) is still not solved.

**Comment by 0crat** [comment]
Job `gh:ammaratef45/attendance#62` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by 0pdd** [comment]
@Bahaaib the puzzle [#66](https://github.com/ammaratef45/Attendance/issues/66) is still not solved; solved: [#64](https://github.com/ammaratef45/Attendance/issues/64).
