### ISSUE TITLE
create a dialog to show scan result

### ISSUE THREAD

**Issue by 0pdd** [ammaratef45/Attendance#64]
The puzzle `62-6055f489` from #62 has to be resolved: 

https://github.com/ammaratef45/Attendance/blob/aff0111f165480de543b270986c85b5ce7272053/attendance/lib/homePage/home_page_view.dart#L5-L5

The puzzle was created by @ammaratef45 on 28-Apr-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#64](https://github.com/ammaratef45/attendance/issues/64) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CH951175M/a0584259-95e8-4fa3-a193-1bd0095cb38b); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0pdd** [comment]
The puzzle `62-6055f489` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#66](https://github.com/ammaratef45/Attendance/issues/66) is still not solved.

**Comment by 0crat** [comment]
Job was finished in 20 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#64](https://github.com/ammaratef45/attendance/issues/64) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)
