### ISSUE TITLE
Fix project lint errors

### ISSUE THREAD

**Issue by ammaratef45** [ammaratef45/Attendance#67]
The project has 234 lint errors that should be fixed.

**Comment by 0crat** [comment]
The job [#67](https://github.com/ammaratef45/attendance/issues/67) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CH951175M/2e398943-1707-4f85-9339-884287d02834); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0pdd** [comment]
@ammaratef45 7 puzzles [#74](https://github.com/ammaratef45/Attendance/issues/74), [#75](https://github.com/ammaratef45/Attendance/issues/75), [#76](https://github.com/ammaratef45/Attendance/issues/76), [#77](https://github.com/ammaratef45/Attendance/issues/77), [#78](https://github.com/ammaratef45/Attendance/issues/78), [#79](https://github.com/ammaratef45/Attendance/issues/79), [#80](https://github.com/ammaratef45/Attendance/issues/80) are still not solved.

**Comment by 0pdd** [comment]
@ammaratef45 6 puzzles [#74](https://github.com/ammaratef45/Attendance/issues/74), [#75](https://github.com/ammaratef45/Attendance/issues/75), [#77](https://github.com/ammaratef45/Attendance/issues/77), [#78](https://github.com/ammaratef45/Attendance/issues/78), [#79](https://github.com/ammaratef45/Attendance/issues/79), [#80](https://github.com/ammaratef45/Attendance/issues/80) are still not solved; solved: [#76](https://github.com/ammaratef45/Attendance/issues/76).

**Comment by 0pdd** [comment]
@ammaratef45 5 puzzles [#75](https://github.com/ammaratef45/Attendance/issues/75), [#77](https://github.com/ammaratef45/Attendance/issues/77), [#78](https://github.com/ammaratef45/Attendance/issues/78), [#79](https://github.com/ammaratef45/Attendance/issues/79), [#80](https://github.com/ammaratef45/Attendance/issues/80) are still not solved; solved: [#74](https://github.com/ammaratef45/Attendance/issues/74), [#76](https://github.com/ammaratef45/Attendance/issues/76).

**Comment by 0pdd** [comment]
@ammaratef45 5 puzzles [#77](https://github.com/ammaratef45/Attendance/issues/77), [#78](https://github.com/ammaratef45/Attendance/issues/78), [#79](https://github.com/ammaratef45/Attendance/issues/79), [#80](https://github.com/ammaratef45/Attendance/issues/80), [#84](https://github.com/ammaratef45/Attendance/issues/84) are still not solved; solved: [#74](https://github.com/ammaratef45/Attendance/issues/74), [#75](https://github.com/ammaratef45/Attendance/issues/75), [#76](https://github.com/ammaratef45/Attendance/issues/76).

**Comment by 0pdd** [comment]
@ammaratef45 4 puzzles [#78](https://github.com/ammaratef45/Attendance/issues/78), [#79](https://github.com/ammaratef45/Attendance/issues/79), [#80](https://github.com/ammaratef45/Attendance/issues/80), [#84](https://github.com/ammaratef45/Attendance/issues/84) are still not solved; solved: [#74](https://github.com/ammaratef45/Attendance/issues/74), [#75](https://github.com/ammaratef45/Attendance/issues/75), [#76](https://github.com/ammaratef45/Attendance/issues/76), [#77](https://github.com/ammaratef45/Attendance/issues/77).

**Comment by 0pdd** [comment]
@ammaratef45 3 puzzles [#79](https://github.com/ammaratef45/Attendance/issues/79), [#80](https://github.com/ammaratef45/Attendance/issues/80), [#84](https://github.com/ammaratef45/Attendance/issues/84) are still not solved; solved: [#74](https://github.com/ammaratef45/Attendance/issues/74), [#75](https://github.com/ammaratef45/Attendance/issues/75), [#76](https://github.com/ammaratef45/Attendance/issues/76), [#77](https://github.com/ammaratef45/Attendance/issues/77), [#78](https://github.com/ammaratef45/Attendance/issues/78).

**Comment by 0crat** [comment]
The job [#67](https://github.com/ammaratef45/attendance/issues/67) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0pdd** [comment]
@ammaratef45 2 puzzles [#80](https://github.com/ammaratef45/Attendance/issues/80), [#84](https://github.com/ammaratef45/Attendance/issues/84) are still not solved; solved: [#74](https://github.com/ammaratef45/Attendance/issues/74), [#75](https://github.com/ammaratef45/Attendance/issues/75), [#76](https://github.com/ammaratef45/Attendance/issues/76), [#77](https://github.com/ammaratef45/Attendance/issues/77), [#78](https://github.com/ammaratef45/Attendance/issues/78), [#79](https://github.com/ammaratef45/Attendance/issues/79).

**Comment by 0pdd** [comment]
@ammaratef45 all 8 puzzles are solved here: [#74](https://github.com/ammaratef45/Attendance/issues/74), [#75](https://github.com/ammaratef45/Attendance/issues/75), [#76](https://github.com/ammaratef45/Attendance/issues/76), [#77](https://github.com/ammaratef45/Attendance/issues/77), [#78](https://github.com/ammaratef45/Attendance/issues/78), [#79](https://github.com/ammaratef45/Attendance/issues/79), [#80](https://github.com/ammaratef45/Attendance/issues/80), [#84](https://github.com/ammaratef45/Attendance/issues/84).
