### ISSUE TITLE
mock data of the session.

### ISSUE THREAD

**Issue by 0pdd** [ammaratef45/Attendance#69]
The puzzle `48-4a4efa8d` from #48 has to be resolved: 

https://github.com/ammaratef45/Attendance/blob/8cf8d697e566842fe560dd452631f7a494b44f0f/attendance/test/api_test.dart#L83-L83

The puzzle was created by @ammaratef45 on 30-Apr-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `48-4a4efa8d` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:ammaratef45/attendance#69` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
