### ISSUE TITLE
Move from firebase to API

### ISSUE THREAD

**Issue by ammaratef45** [ammaratef45/Attendance#9]
use [this api](https://github.com/ammaratef45/Attendance-API) instead of firebase, that would require migrating a lot of functionality, use puzzles to simplify the work and divide it.

**Comment by 0crat** [comment]
Job [#9](https://github.com/ammaratef45/attendance/issues/9) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) everybody who has role `DEV` is banned at [#9](https://github.com/ammaratef45/attendance/issues/9); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) everybody who has role `DEV` is banned at [#9](https://github.com/ammaratef45/attendance/issues/9); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) everybody who has role `DEV` is banned at [#9](https://github.com/ammaratef45/attendance/issues/9); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) everybody who has role `DEV` is banned at [#9](https://github.com/ammaratef45/attendance/issues/9); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
The job [#9](https://github.com/ammaratef45/attendance/issues/9) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CH951175M/c05d39db-f4fc-42e0-8738-02b051a4d13d); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0pdd** [comment]
@ammaratef45 7 puzzles [#45](https://github.com/ammaratef45/Attendance/issues/45), [#46](https://github.com/ammaratef45/Attendance/issues/46), [#47](https://github.com/ammaratef45/Attendance/issues/47), [#48](https://github.com/ammaratef45/Attendance/issues/48), [#49](https://github.com/ammaratef45/Attendance/issues/49), [#50](https://github.com/ammaratef45/Attendance/issues/50), [#51](https://github.com/ammaratef45/Attendance/issues/51) are still not solved.

**Comment by 0crat** [comment]
The job [#9](https://github.com/ammaratef45/attendance/issues/9) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0pdd** [comment]
@ammaratef45 6 puzzles [#45](https://github.com/ammaratef45/Attendance/issues/45), [#47](https://github.com/ammaratef45/Attendance/issues/47), [#48](https://github.com/ammaratef45/Attendance/issues/48), [#49](https://github.com/ammaratef45/Attendance/issues/49), [#50](https://github.com/ammaratef45/Attendance/issues/50), [#51](https://github.com/ammaratef45/Attendance/issues/51) are still not solved; solved: [#46](https://github.com/ammaratef45/Attendance/issues/46).

**Comment by 0pdd** [comment]
@ammaratef45 8 puzzles [#45](https://github.com/ammaratef45/Attendance/issues/45), [#47](https://github.com/ammaratef45/Attendance/issues/47), [#48](https://github.com/ammaratef45/Attendance/issues/48), [#49](https://github.com/ammaratef45/Attendance/issues/49), [#50](https://github.com/ammaratef45/Attendance/issues/50), [#59](https://github.com/ammaratef45/Attendance/issues/59), [#60](https://github.com/ammaratef45/Attendance/issues/60), [#61](https://github.com/ammaratef45/Attendance/issues/61) are still not solved; solved: [#46](https://github.com/ammaratef45/Attendance/issues/46), [#51](https://github.com/ammaratef45/Attendance/issues/51).

**Comment by 0pdd** [comment]
@ammaratef45 10 puzzles [#45](https://github.com/ammaratef45/Attendance/issues/45), [#47](https://github.com/ammaratef45/Attendance/issues/47), [#49](https://github.com/ammaratef45/Attendance/issues/49), [#50](https://github.com/ammaratef45/Attendance/issues/50), [#59](https://github.com/ammaratef45/Attendance/issues/59), [#60](https://github.com/ammaratef45/Attendance/issues/60), [#61](https://github.com/ammaratef45/Attendance/issues/61), [#69](https://github.com/ammaratef45/Attendance/issues/69), [#70](https://github.com/ammaratef45/Attendance/issues/70), [#71](https://github.com/ammaratef45/Attendance/issues/71) are still not solved; solved: [#46](https://github.com/ammaratef45/Attendance/issues/46), [#48](https://github.com/ammaratef45/Attendance/issues/48), [#51](https://github.com/ammaratef45/Attendance/issues/51).

**Comment by 0pdd** [comment]
@ammaratef45 9 puzzles [#45](https://github.com/ammaratef45/Attendance/issues/45), [#49](https://github.com/ammaratef45/Attendance/issues/49), [#50](https://github.com/ammaratef45/Attendance/issues/50), [#59](https://github.com/ammaratef45/Attendance/issues/59), [#60](https://github.com/ammaratef45/Attendance/issues/60), [#61](https://github.com/ammaratef45/Attendance/issues/61), [#69](https://github.com/ammaratef45/Attendance/issues/69), [#70](https://github.com/ammaratef45/Attendance/issues/70), [#71](https://github.com/ammaratef45/Attendance/issues/71) are still not solved; solved: [#46](https://github.com/ammaratef45/Attendance/issues/46), [#47](https://github.com/ammaratef45/Attendance/issues/47), [#48](https://github.com/ammaratef45/Attendance/issues/48), [#51](https://github.com/ammaratef45/Attendance/issues/51).

**Comment by 0pdd** [comment]
@ammaratef45 10 puzzles [#49](https://github.com/ammaratef45/Attendance/issues/49), [#50](https://github.com/ammaratef45/Attendance/issues/50), [#59](https://github.com/ammaratef45/Attendance/issues/59), [#60](https://github.com/ammaratef45/Attendance/issues/60), [#61](https://github.com/ammaratef45/Attendance/issues/61), [#69](https://github.com/ammaratef45/Attendance/issues/69), [#70](https://github.com/ammaratef45/Attendance/issues/70), [#71](https://github.com/ammaratef45/Attendance/issues/71), [#94](https://github.com/ammaratef45/Attendance/issues/94), [#95](https://github.com/ammaratef45/Attendance/issues/95) are still not solved; solved: [#45](https://github.com/ammaratef45/Attendance/issues/45), [#46](https://github.com/ammaratef45/Attendance/issues/46), [#47](https://github.com/ammaratef45/Attendance/issues/47), [#48](https://github.com/ammaratef45/Attendance/issues/48), [#51](https://github.com/ammaratef45/Attendance/issues/51).

**Comment by 0pdd** [comment]
@ammaratef45 9 puzzles [#50](https://github.com/ammaratef45/Attendance/issues/50), [#59](https://github.com/ammaratef45/Attendance/issues/59), [#60](https://github.com/ammaratef45/Attendance/issues/60), [#61](https://github.com/ammaratef45/Attendance/issues/61), [#69](https://github.com/ammaratef45/Attendance/issues/69), [#70](https://github.com/ammaratef45/Attendance/issues/70), [#71](https://github.com/ammaratef45/Attendance/issues/71), [#94](https://github.com/ammaratef45/Attendance/issues/94), [#95](https://github.com/ammaratef45/Attendance/issues/95) are still not solved; solved: [#45](https://github.com/ammaratef45/Attendance/issues/45), [#46](https://github.com/ammaratef45/Attendance/issues/46), [#47](https://github.com/ammaratef45/Attendance/issues/47), [#48](https://github.com/ammaratef45/Attendance/issues/48), [#49](https://github.com/ammaratef45/Attendance/issues/49), [#51](https://github.com/ammaratef45/Attendance/issues/51).

**Comment by 0pdd** [comment]
@ammaratef45 7 puzzles [#104](https://github.com/ammaratef45/Attendance/issues/104), [#105](https://github.com/ammaratef45/Attendance/issues/105), [#70](https://github.com/ammaratef45/Attendance/issues/70), [#94](https://github.com/ammaratef45/Attendance/issues/94), [#95](https://github.com/ammaratef45/Attendance/issues/95), [#98](https://github.com/ammaratef45/Attendance/issues/98), [#99](https://github.com/ammaratef45/Attendance/issues/99) are still not solved; solved: [#100](https://github.com/ammaratef45/Attendance/issues/100), [#101](https://github.com/ammaratef45/Attendance/issues/101), [#45](https://github.com/ammaratef45/Attendance/issues/45), [#46](https://github.com/ammaratef45/Attendance/issues/46), [#47](https://github.com/ammaratef45/Attendance/issues/47), [#48](https://github.com/ammaratef45/Attendance/issues/48), [#49](https://github.com/ammaratef45/Attendance/issues/49), [#50](https://github.com/ammaratef45/Attendance/issues/50), [#51](https://github.com/ammaratef45/Attendance/issues/51), [#59](https://github.com/ammaratef45/Attendance/issues/59), [#60](https://github.com/ammaratef45/Attendance/issues/60), [#61](https://github.com/ammaratef45/Attendance/issues/61), [#69](https://github.com/ammaratef45/Attendance/issues/69), [#71](https://github.com/ammaratef45/Attendance/issues/71).

**Comment by 0pdd** [comment]
@ammaratef45 6 puzzles [#104](https://github.com/ammaratef45/Attendance/issues/104), [#105](https://github.com/ammaratef45/Attendance/issues/105), [#94](https://github.com/ammaratef45/Attendance/issues/94), [#95](https://github.com/ammaratef45/Attendance/issues/95), [#98](https://github.com/ammaratef45/Attendance/issues/98), [#99](https://github.com/ammaratef45/Attendance/issues/99) are still not solved; solved: [#100](https://github.com/ammaratef45/Attendance/issues/100), [#101](https://github.com/ammaratef45/Attendance/issues/101), [#45](https://github.com/ammaratef45/Attendance/issues/45), [#46](https://github.com/ammaratef45/Attendance/issues/46), [#47](https://github.com/ammaratef45/Attendance/issues/47), [#48](https://github.com/ammaratef45/Attendance/issues/48), [#49](https://github.com/ammaratef45/Attendance/issues/49), [#50](https://github.com/ammaratef45/Attendance/issues/50), [#51](https://github.com/ammaratef45/Attendance/issues/51), [#59](https://github.com/ammaratef45/Attendance/issues/59), [#60](https://github.com/ammaratef45/Attendance/issues/60), [#61](https://github.com/ammaratef45/Attendance/issues/61), [#69](https://github.com/ammaratef45/Attendance/issues/69), [#70](https://github.com/ammaratef45/Attendance/issues/70), [#71](https://github.com/ammaratef45/Attendance/issues/71).
